### ISSUE TITLE
cleartext pw

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity-lab/image-factory#1]
im not sure if its of any concern but this looks like it contains a pw in plain text:

`cookbooks/prometheus/recipes/node_exporter.rb`

**Comment by enzoh** [comment]
Thanks for pointing this out and no, this is not any concern. In-fact the root password is the word root. Remote access is guarded by SSH. This repository is more of an example. It's up to your data center engineer to determine what additional hardening is required, which may depend on the layout of your rack, physical security, etc.

**Comment by letmejustputthishere** [comment]
thank you for the explanation
